{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    app: freeai
    {{- toYaml .Values.global.commonLabels | nindent 4 }}
{{- end }}
